version: '3.9'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
